### ISSUE TITLE
Add TravisCI

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-bootstrapmfa#3]

**Comment by robbieaverill** [comment]
@Firesphere can you kick this off by enabling it on Travis? I'm happy to set up the config for it in this repo, but it needs a repository admin to enable it first. https://travis-ci.org/Firesphere/silverstripe-bootstrapmfa

**Comment by Firesphere** [comment]
Have activated, but no YML yet

**Comment by robbieaverill** [comment]
Thank you
