### ISSUE TITLE
Backport to SilverStripe 3

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-bootstrapmfa#31]
Use the Bootstrap3MFA to backport to SS3, or use the SS3 module entirely and connect it to this Repo

**Comment by brynwhyman** [comment]
We should include documentation as part of this issue.

**Comment by brynwhyman** [comment]
We created a spike to investigate this, but have since decided to proceed (outside of the spike)
https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/9
