### ISSUE TITLE
Hash backup codes with SHA-512

### ISSUE THREAD

**Issue by chillu** [Firesphere/silverstripe-bootstrapmfa#40]
The current Blowfish default is safe, but not NZISM compliant - see https://github.com/silverstripe/cwp-core/issues/51. We should use SHA-512 here instead. Since there's only one hashing algo per user, applied for both passwords and backup codes, we need to introduce this in a way which auto-changes the user's password to SHA-512 as well, either before or during generation of backup codes.

This will likely require a new `PasswordEncryptor_SHA512` class to be added to SilverStripe Framework.

**Comment by Firesphere** [comment]
Backup codes are hashed with the set hashing method in the config, so if SHA512 is set as hashing method, it is used for the backup codes. There is no explicit setting in this module that sets the hashing method

**Comment by brynwhyman** [comment]
Looking at #5 we're now looking at uses existing password hashing methods. Following this issue, using an updated hashing algorithm should move to cwp core.

**Comment by robbieaverill** [comment]
Yep we decided that this module should use whatever the project level configuration is for a password hashing algorithm. CWP core can specify that to be SHA512 if it's necessary for NZISM compliance, and we could add something stronger to SilverStripe core by default. This module would use whatever is configured to hash with.

One question that's worth asking though is that if someone has configured a weak algorithm, should this module ignore that and use some kind of baseline? E.g. if my project uses a Caesar shift or something, BootstrapMFA says "nah, I'll use SHA512 please"
