### ISSUE TITLE
Password and backup codes use separate salt

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-bootstrapmfa#5]
Currently uses Member::encryptWithUserSettings. These should be separated so that they can be reset without reliance on the other.

Create new hashing method for each. We can probably use an existing method, either one provided by php or something existing in SilverStripe security.

Resetting either backup codes or a password would re-hash

**Comment by brynwhyman** [comment]
My understanding is in keeping this functionality, if the user's password (and salt) is reset, the backup codes will also be reset. We're in the process of finalising the user flows and reviewing what the impact of this would be.

**Comment by robbieaverill** [comment]
>We can probably use an existing method, either one provided by php or something existing in SilverStripe security.

I think @chillu mentioned in another issue that we should use whatever is the configured "encryption" method in core rather than specifying something different for this module
